name: Issue Manager

on:
  issues:
    types:
      - opened
      - edited
      - deleted
      - transferred
      - closed
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: write
  id-token: write

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: npm install
        run: npm install

      - name: actions.ts
        run: npx tsx actions.ts
        env:
          GITHUB_ISSUE: ${{ toJson(github.event.issue) }}

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update Issue Database
          committer_name: GitHub Actions
          committer_email: actions@github.com
