on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: npm install
        run: npm install
